export const GET_TODOS_INIT = "GET_TODOS_INIT";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAIL = "GET_TODOS_FAIL";

export const ADD_TODO_INIT = "ADD_TODO_INIT";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAIL = "ADD_TODO_FAIL";

export const DELETE_TODO = "DELETE_TODO";
